# Generated by Django 6.0.1 on 2026-01-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='desription',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Опис'),
        ),
    ]
