# Generated by Django 6.0.1 on 2026-02-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profile_phone_number_alter_action_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(choices=[('CB', 'CreateBooking'), ('RB', 'ReadBooking'), ('UB', 'UpdateBooking')], default='RB', help_text='Введіть назву дії', max_length=100, verbose_name='Дозволена дія'),
        ),
    ]
