# Generated by Django 6.0.1 on 2026-02-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_alter_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
        migrations.AlterField(
            model_name='profile',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='Profile.subject', verbose_name='Список предметів'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Profile.position'),
        ),
    ]
