# Generated by Django 6.0.1 on 2026-02-10 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profile_position_alter_profile_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Назва класу')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Опис класу')),
                ('subjects', models.ManyToManyField(blank=True, default=None, null=True, to='Profile.subject', verbose_name='Список предметів')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='class_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.classroom'),
        ),
    ]
