# Generated by Django 6.0.1 on 2026-02-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_classroom_profile_class_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='position',
            new_name='positions',
        ),
    ]
