# Generated by Django 6.0.1 on 2026-02-23 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_rename_position_profile_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subjects',
        ),
        migrations.AlterField(
            model_name='profile',
            name='class_room',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.classroom'),
        ),
    ]
