# Generated by Django 6.0.1 on 2026-02-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_remove_profile_subjects_alter_profile_class_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, default=None, to='Profile.subject', verbose_name='Список предметів'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='positions',
            field=models.ManyToManyField(blank=True, default=None, to='Profile.position'),
        ),
    ]
