# Generated by Django 6.0.1 on 2026-02-23 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0008_alter_classroom_subjects_alter_profile_positions'),
        ('Resource', '0002_alter_resource_desription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_url', models.URLField(blank=True, default=None, max_length=1000, null=True, verbose_name='Посилання на зустріч')),
                ('day', models.CharField(max_length=20, verbose_name='День тижня')),
                ('number', models.PositiveIntegerField(verbose_name='Година')),
                ('study', models.PositiveIntegerField(verbose_name='Клас')),
                ('resource', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Resource.resource', verbose_name='Кабінет')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.subject', verbose_name='Предмет')),
            ],
        ),
    ]
