# Generated by Django 6.0 on 2026-02-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Понеділок', 'Понеділок'), ('Вівторок', 'Вівторок'), ('Середа', 'Середа'), ('Четвер', 'Четвер'), ("П'ятниця", "П'ятниця")], max_length=20, verbose_name='День тижня'),
        ),
    ]
