# Generated by Django 6.0.1 on 2026-01-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, default=True, max_length=255, null=True, verbose_name='інформація від адміністрації'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Booking.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='bookinglog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата й час події'),
        ),
    ]
